apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: houjiahao123/mystore-warehouse
      context: bookstore-servicemesh-domain-warehouse
    - image: houjiahao123/mystore-authentication
      context: bookstore-servicemesh-domain-authentication
    - image: houjiahao123/mystore-account
      context: bookstore-servicemesh-domain-account
    - image: houjiahao123/mystore-payment
      context: bookstore-servicemesh-domain-payment
    - image: houjiahao123/mystore-frontend
      context: bookstore-servicemesh-domain-frontend
deploy:
  kubectl:
    manifests:
      - ./mystore-kubernetes-manifests/mystore-namespaces.yaml
      - ./mystore-kubernetes-manifests/*.yml
      - ./mystore-istio-manifests/*.yaml
  statusCheckDeadlineSeconds: 20000
