apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: bookstore-servicemesh
  labels:
    app: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
  - port: 80
    name: http-server
    targetPort: http-server
