apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-servicemesh-domain-payment
  namespace: bookstore-servicemesh
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: book-admin
      containers:
        - name: payment
          image: icyfenix/bookstore-istio-domain-payment
          ports:
            - name: http-server
              containerPort: 80
          volumeMounts:
            - name: payment-config
              mountPath: config
          env:
            - name: PORT
              value: "80"
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
      volumes:
        - name: payment-config
          configMap:
            name: payment
            items:
              - key: application.yaml
                path: application.yaml
