apiVersion: v1
kind: Service
metadata:
  name: warehouse
  namespace: bookstore-servicemesh
  labels:
    app: warehouse
spec:
  type: ClusterIP
  selector:
    app: warehouse
  ports:
  - port: 80
    name: http-server
    targetPort: http-server
