apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: bookstore-servicemesh
  labels:
    app: authentication
spec:
  type: ClusterIP
  selector:
    app: authentication
  ports:
  - port: 80
    name: http-server
    targetPort: http-server
