apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: book-admin-role-binding
  namespace: bookstore-servicemesh
roleRef:
  kind: Role
  name: book-admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: book-admin
    namespace: bookstore-servicemesh
