apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bookstore-servicemesh
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 80
    name: http-server
    targetPort: http-server
