kind: ConfigMap
apiVersion: v1
metadata:
  name: frontend
  namespace: bookstore-servicemesh
data:
  application.yaml: |-
    server:
      port: ${PORT:80}

    logging:
      level:
        root: INFO
